spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_HOST:localhost}:9092

app:
  kafka:
    kafkaOrderTopic: "order-topic"
    kafkaOrderStatusTopic: "order-status-topic"
    kafkaOrderStatusGroupId: "kafka-status-group-id"
